### ISSUE TITLE
Error today and tomorrow sensor

### ISSUE THREAD

**Issue by Sholofly** [xirixiz/home-assistant#4]
Hi Bram,

I'm experiencing the next error after updating to 1.1.6:

```
2018-12-22 22:15:15 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_tomorrow fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/mijnafvalwijzer.py", line 114, in update
    self.data.update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sensor/mijnafvalwijzer.py", line 181, in update
    trashType[name] = labelToday
TypeError: unhashable type: 'dict'
```

**Comment by xirixiz** [comment]
Hi Sholofy,

Upgrading to 1.1.6, the latest version is 2.0.6... could you upgrade to that version and try again please?
